[package]
name = "PVZ_ZombieDraw"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0-alpha.2"
winapi = { version = "0.3", features = ["winuser", "memoryapi", "processthreadsapi", "handleapi", "errhandlingapi", "psapi", "winbase", "windef"] }
